### ISSUE TITLE
External Observables

### ISSUE THREAD

**Issue by ryanking1809** [alloc/wana#33]
Is it possible to trigger the `auto` function with external observables?

Say I had an object with `onRead` and `onUpdate` callbacks. Is there some way to do something like the following?

```js
externalObservable.onRead(() => tellWanaObjectRead())
externalObservable.onUpdate(() => tellWanaObjectUpdated())

auto(() => {
    console.log(externalObservable.value)
})

externalObservable.value = 'newVal'
// -> console logs 'newVal'
```

**Comment by aleclarson** [comment]
```ts
const reaction = auto(() => {...})

foreignObservable.onUpdate(() => {
  // Force the reaction to rerun synchronously.
  reaction.rerun()
})
```

If your `auto` reaction depends on multiple foreign observables, you'll have to do your own batching *or* rerun the reaction once per foreign observable (resulting in unnecessary computation). When using wana observables, batching is done automatically with a microtask (same thing that promises use).

I'm not sure what you expect from your `onRead` listener. Reactions created with `auto` have no value to read.

**Comment by ryanking1809** [comment]
Thanks, that would be one way to do it.

I was thinking when you have `obs = o({value: 3})` and `auto(() => obs.value))` there must be something that informs `auto` that `obs.value` was observed / read. But now I think about it more, I don't think it would be possible to utilise that externally to wana.

I might also see if I can somehow extend the object to become a wana observable 🤔

**Comment by ryanking1809** [comment]
Any reason I shouldn't do the following?

```js
const reaction = auto(() => {...})

foreignObservable.onUpdate(() => {
  reaction.dirty = true
})
```

I'm using getters so it'll be more like.
```js
const obs = o({ get val() => {...} })

foreignObservable.onUpdate(() => {
  Object.getOwnPropertyDescriptor(obs, "val").get.auto.dirty = true
})
```

**Comment by aleclarson** [comment]
Note that `o({ get val() {…} })` doesn't make `val` observable. Since observable getters (eg: `o(() => {…})`) need their `dispose` method called when no longer needed (to prevent memory leaks), and observable objects (eg: `o({ … })`) have no `dispose` method, it's just not possible (unless you set that up manually).

That said, setting `auto.dirty = true` directly would backfire, because it would prevent the reaction from re-running in response to changes. What you really want is the `auto.clear` method, which triggers the `auto.onDirty` method when `auto.dirty` is false.

https://github.com/alloc/wana/blob/97f81e9b9a837b601e27061d73e6c35993e6e2dd/src/auto.ts#L137-L142
